import requests
from bs4 import BeautifulSoup
import json, re, time, os, pathlib, random, html as _html
from datetime import datetime, date, timedelta

try:
    import brotli  # noqa: F401
    _ACCEPT_ENCODING = "gzip, deflate, br"
except ImportError:
    try:
        import brotlicffi  # noqa: F401
        _ACCEPT_ENCODING = "gzip, deflate, br"
    except ImportError:
        _ACCEPT_ENCODING = "gzip, deflate"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36",
    "Accept-Language": "es-ES,es;q=0.9,en;q=0.6",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
    # Solo pedimos brotli si podemos descomprimirlo: si no, el HTML llega ilegible
    # y el scraping devuelve cero eventos con un HTTP 200 enganoso.
    "Accept-Encoding": _ACCEPT_ENCODING,
    "Upgrade-Insecure-Requests": "1",
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "none",
    "Sec-Fetch-User": "?1",
    "Sec-CH-UA": '"Chromium";v="140", "Not=A?Brand";v="24"',
    "Sec-CH-UA-Mobile": "?0",
    "Sec-CH-UA-Platform": '"macOS"',
    "Cache-Control": "no-cache",
    "Pragma": "no-cache",
}

# Sesion unica: reutiliza conexion y conserva cookies (muchos WAF las exigen)
SESSION = requests.Session()
SESSION.headers.update(HEADERS)

# Diagnostico por dominio, para que los logs de Actions digan QUE falla y por que
DIAG = {}

# Senales de muro anti-bot devuelto con codigo 200
BLOCK_SIGNS = (
    "just a moment", "cf-browser-verification", "cf_chl_opt", "checking your browser",
    "attention required", "access denied", "acceso denegado", "request unsuccessful",
    "generated by wordfence", "your access to this site has been limited",
    "ddos protection", "enable javascript and cookies to continue",
    # Webs caidas que devuelven 200 con la pagina del hosting: sin esto, el
    # scraper las cuenta como "fuente vacia" y se busca un fallo inexistente.
    "account suspended", "cuenta suspendida",
    "error establishing a database connection",
    "this site is temporarily unavailable", "web en mantenimiento",
)

def _looks_blocked(text):
    low = text[:4000].lower()
    return next((sign for sign in BLOCK_SIGNS if sign in low), None)

# Load salas for name normalization
_SALAS = []
_salas_file = pathlib.Path(__file__).parent.parent / 'salas.json'
if _salas_file.exists():
    _SALAS = json.loads(_salas_file.read_text())['salas']

def normalize_sala(sala_raw):
    if not sala_raw: return sala_raw
    s = sala_raw.lower().strip()
    for sala in _SALAS:
        for kw in sala['keywords']:
            if kw.lower() in s:
                return sala['nombre']
    return sala_raw

MONTHS = {
    "enero":1,"febrero":2,"marzo":3,"abril":4,"mayo":5,"junio":6,
    "julio":7,"agosto":8,"septiembre":9,"octubre":10,"noviembre":11,"diciembre":12,
    "ene":1,"feb":2,"mar":3,"abr":4,"may":5,"jun":6,
    "jul":7,"ago":8,"sep":9,"oct":10,"nov":11,"dic":12,
    "jan":1,"apr":4,"aug":8,"dec":12
}

def normalize(t):
    if not t: return ""
    # Decode HTML entities (e.g. &#8211; -> —, &amp; -> &)
    import html
    t = html.unescape(str(t))
    return " ".join(t.split()).strip()

def parse_date(text):
    if not text: return None
    t = text.lower().strip()
    m = re.search(r'(\d{4})-(\d{2})-(\d{2})', t)
    if m: return m.group(0)
    m = re.search(r'(\d{1,2})/(\d{1,2})/(\d{4})', t)
    if m: return f"{m.group(3)}-{int(m.group(2)):02d}-{int(m.group(1)):02d}"
    m = re.search(r'(\d{1,2})\s+(?:de\s+)?(\w+)\s+(?:de\s+)?(\d{4})', t)
    if m:
        mon = MONTHS.get(m.group(2)[:3])
        if mon: return f"{m.group(3)}-{mon:02d}-{int(m.group(1)):02d}"
    m = re.search(r'(\d{1,2})\s+(?:de\s+)?(\w+)', t)
    if m:
        mon = MONTHS.get(m.group(2)[:3])
        if mon:
            y = date.today().year
            d = int(m.group(1))
            candidate = f"{y}-{mon:02d}-{d:02d}"
            if candidate < date.today().isoformat():
                candidate = f"{y+1}-{mon:02d}-{d:02d}"
            return candidate
    return None

def parse_time(text):
    if not text: return ""
    m = re.search(r'(\d{1,2})[:\.](\d{2})', text)
    if m: return f"{int(m.group(1)):02d}:{m.group(2)}"
    return ""

def get(url, timeout=(20, 25), retries=2):
    """GET con reintentos, espera creciente y registro de diagnostico por dominio.

    timeout es (conexion, lectura). Con 8 s de conexion el job bajaba mucho de
    duracion, pero aragonenvivo.com tarda mas que eso en aceptar la conexion desde
    el runner de GitHub y se perdia entera: 20 s deja margen y aun asi un host
    muerto cuesta ~45 s en vez de los 95 s de antes.
    """
    dom = re.sub(r"^www\.", "", (url.split("/")[2] if "://" in url else url))
    last = ""
    for attempt in range(retries):
        t0 = time.time()
        try:
            r = SESSION.get(url, timeout=timeout, allow_redirects=True)
            ms = int((time.time() - t0) * 1000)
            if r.status_code >= 400:
                last = f"HTTP {r.status_code}"
                DIAG[dom] = {"estado": last, "ms": ms, "bytes": len(r.content)}
                # 404/410 no se arreglan reintentando: la URL ya no existe
                if r.status_code in (404, 410):
                    print(f"  WARN {url[:70]}: {last} (URL inexistente, no reintento)")
                    return None
            else:
                blocked = _looks_blocked(r.text)
                if blocked:
                    last = f"muro anti-bot ({blocked!r})"
                    DIAG[dom] = {"estado": last, "ms": ms, "bytes": len(r.content)}
                else:
                    DIAG[dom] = {"estado": "OK", "ms": ms, "bytes": len(r.content)}
                    return r
        except Exception as e:
            ms = int((time.time() - t0) * 1000)
            last = f"{type(e).__name__}: {str(e)[:90]}"
            DIAG[dom] = {"estado": last, "ms": ms, "bytes": 0}
        if attempt < retries - 1:
            time.sleep(2 ** attempt + random.uniform(0, 1.2))
    print(f"  WARN {url[:70]}: {last}")
    return None

# Frases de navegacion que el scraping recoge como si fueran conciertos
JUNK_TITLES = {
    "ver agenda completa", "ver agenda", "agenda completa", "ver todos", "ver todo",
    "ver mas", "ver más", "mas info", "más info", "mas informacion", "más información",
    "leer mas", "leer más", "proximos eventos", "próximos eventos", "todos los eventos",
    "comprar entradas", "entradas", "cartelera", "programacion", "programación",
    "inicio", "contacto", "conciertos", "eventos", "agenda", "sin categoria", "sin categoría",
}

def _slug(t):
    t = normalize(t or "").lower().strip()
    for a, b in (("á","a"),("é","e"),("í","i"),("ó","o"),("ú","u"),("ü","u"),("ñ","n")):
        t = t.replace(a, b)
    return re.sub(r"[^a-z0-9 ]", "", t).strip()

# Nombres y alias de salas: si el "titulo" es solo eso, es un enlace a la sala, no un concierto
_SALA_SLUGS = set()
for _s in _SALAS:
    _SALA_SLUGS.add(_slug(_s.get("nombre", "")))
    for _kw in _s.get("keywords", []):
        _SALA_SLUGS.add(_slug(_kw))
_SALA_SLUGS.discard("")

# Rutas de taxonomia (lugares, categorias, etiquetas): son fichas de sala o de
# seccion, nunca un concierto concreto. aragonmusical.com/lugares/... es el caso tipico.
JUNK_URL_PARTS = (
    "/lugares/", "/lugar/", "/venue/", "/venues/", "/salas/", "/sala/",
    "/categoria/", "/category/", "/tag/", "/etiqueta/", "/author/", "/autor/",
)

def is_junk_url(url):
    low = (url or "").lower()
    return any(part in low for part in JUNK_URL_PARTS)

def is_junk_title(titulo):
    sl = _slug(titulo)
    if len(sl) < 3: return True
    if sl in JUNK_TITLES: return True
    if sl in _SALA_SLUGS: return True
    if re.fullmatch(r"(ver|abrir|mira)( .{0,20})?", sl): return True
    return False

def make_event(titulo, fecha, hora, sala, url, imagen="", descripcion=""):
    return {
        "titulo": normalize(titulo),
        "fecha": fecha or "",
        "hora": hora or "",
        "sala": normalize_sala(normalize(sala)),
        "url": url or "",
        "imagen": imagen or "",
        "descripcion": normalize(descripcion),
    }

def extract_tribe(soup, sala_default, base_url):
    events = []
    articles = []
    for sel in ["article.type-tribe_events","article.tribe_events_cat",
                ".tribe-events-calendar-list__event",".tribe-events-loop article",
                "article[class*='tribe']",".events-archive article"]:
        items = soup.select(sel)
        if items: articles = items; break
    for art in articles:
        title_el = art.select_one("h2 a, h3 a, .entry-title a, .tribe-events-list-event-title a")
        # Try multiple date selectors aggressively
        date_el = art.select_one(
            "time[datetime], abbr[title], .tribe-event-date-start, "
            "[class*='tribe-event-date'], [class*='event-date'], "
            "[class*='date-start'], .entry-date, .published"
        )
        loc_el = art.select_one(".tribe-venue, [class*='tribe-venue'], [class*='venue']")
        img_el = art.select_one("img")
        link_el = art.select_one("a[href]")
        title = normalize(title_el.get_text()) if title_el else ""
        if not title or len(title) < 3: continue
        
        # Get date from multiple sources
        fecha_raw = ""
        if date_el:
            fecha_raw = (date_el.get("datetime","") or 
                        date_el.get("title","") or 
                        date_el.get("content","") or 
                        date_el.get_text())
        
        # Also check link URL for date pattern (many WP sites have /2025/05/15/ in URL)
        if not parse_date(fecha_raw) and link_el:
            href_date = link_el.get("href","")
            m = re.search(r"/(202[0-9])/(\d{2})/(\d{2})/", href_date)
            if m:
                fecha_raw = f"{m.group(1)}-{m.group(2)}-{m.group(3)}"
        
        hora_el = art.select_one("[class*='time'], .tribe-events-schedule, [class*='hora']")
        hora_raw = hora_el.get_text() if hora_el else fecha_raw
        sala = normalize(loc_el.get_text()) if loc_el else sala_default
        href = link_el["href"] if link_el else base_url
        if href and not href.startswith("http"): href = base_url.rstrip("/") + "/" + href.lstrip("/")
        img = (img_el.get("src","") or img_el.get("data-src","")) if img_el else ""
        events.append(make_event(title, parse_date(fecha_raw) or "", parse_time(hora_raw), sala or sala_default, href, img))
    return events


def _jsonld_bloques(texto):
    for bruto in re.findall(r"<script[^>]+application/ld\+json[^>]*>(.*?)</script>", texto, re.S):
        try:
            yield json.loads(_html.unescape(bruto.strip()))
        except Exception:
            continue

def _jsonld_eventos(dato):
    """Recorre el arbol JSON-LD y devuelve los nodos de tipo Event."""
    if isinstance(dato, list):
        for d in dato:
            yield from _jsonld_eventos(d)
    elif isinstance(dato, dict):
        if "Event" in str(dato.get("@type", "")):
            yield dato
        for clave in ("@graph", "itemListElement", "item", "subEvent"):
            if clave in dato:
                yield from _jsonld_eventos(dato[clave])

def scrape_jsonld(url, nombre_fuente, solo_zaragoza=True):
    """Lee la agenda de los datos estructurados schema.org de la pagina.

    Es mas estable que raspar el HTML: el marcado cambia de diseno a menudo, el
    JSON-LD casi nunca, y trae fecha con hora, sala y localidad ya separadas.
    """
    r = get(url)
    if not r:
        print(f"  {nombre_fuente}: sin respuesta")
        return []
    evs, fuera = [], 0
    for bloque in _jsonld_bloques(r.text):
        for ev in _jsonld_eventos(bloque):
            titulo = normalize(str(ev.get("name") or ""))
            inicio = str(ev.get("startDate") or "")
            if not titulo or len(titulo) < 3 or not inicio: continue
            fecha = parse_date(inicio[:10]) or ""
            hora = ""
            mh = re.search(r"T(\d{2}):(\d{2})", inicio)
            if mh and mh.group(0) != "T00:00":
                hora = f"{mh.group(1)}:{mh.group(2)}"
            lugar = ev.get("location") or {}
            sala = normalize(str(lugar.get("name") or "")) if isinstance(lugar, dict) else ""
            ciudad = ""
            if isinstance(lugar, dict):
                dirn = lugar.get("address")
                if isinstance(dirn, dict): ciudad = str(dirn.get("addressLocality") or "")
                elif isinstance(dirn, str): ciudad = dirn
            if solo_zaragoza and not _es_zaragoza_ciudad(ciudad, sala):
                fuera += 1
                continue
            enlace = str(ev.get("url") or url)
            imagen = ev.get("image")
            if isinstance(imagen, list): imagen = imagen[0] if imagen else ""
            if isinstance(imagen, dict): imagen = imagen.get("url", "")
            evs.append(make_event(titulo, fecha, hora, sala or "Zaragoza", enlace, str(imagen or "")))
    con_hora = sum(1 for e in evs if e["hora"])
    print(f"  {nombre_fuente}: {len(evs)} ({con_hora} con hora, {fuera} fuera de la ciudad)")
    return evs

def scrape_jacksonlive():
    return scrape_jsonld("https://www.jacksonlive.es/zaragoza", "jacksonlive")

def scrape_generic(url, sala_name, base_url):
    r = get(url)
    if not r: return []
    soup = BeautifulSoup(r.text, "html.parser")
    evs = extract_tribe(soup, sala_name, base_url)
    if not evs:
        for art in soup.select("article, .event, [class*='event'], [class*='concierto']"):
            title_el = art.select_one("h2 a, h3 a, h4 a, .entry-title a, a")
            date_el = art.select_one(
                "time, [class*='date'], [class*='fecha'], "
                "abbr[title], [itemprop='startDate'], [class*='cuando']"
            )
            img_el = art.select_one("img")
            link_el = art.select_one("a[href]")
            title = normalize(title_el.get_text()) if title_el else ""
            if not title or len(title) < 3: continue
            fecha_raw = ""
            if date_el:
                fecha_raw = (date_el.get("datetime","") or date_el.get("title","") or
                            date_el.get("content","") or date_el.get_text())
            # Try URL date pattern
            if not parse_date(fecha_raw) and link_el:
                m = re.search(r"/(202[0-9])/(\d{2})/(\d{2})/", link_el.get("href",""))
                if m: fecha_raw = f"{m.group(1)}-{m.group(2)}-{m.group(3)}"
            href = link_el["href"] if link_el else base_url
            if href and not href.startswith("http"): href = base_url.rstrip("/") + "/" + href.lstrip("/")
            evs.append(make_event(title, parse_date(fecha_raw) or "", parse_time(fecha_raw),
                sala_name, href, img_el.get("src","") if img_el else ""))
    return evs


def scrape_zgzconciertos():
    evs = scrape_generic("https://zgzconciertos.com/agenda/lista/", "Zaragoza", "https://zgzconciertos.com")
    # Enrich hora for events missing it (visit individual pages)
    enriched = 0
    for ev in evs:
        if not ev.get("hora") and ev.get("url") and enriched < 15:
            r = get(ev["url"], timeout=8)
            if r:
                from bs4 import BeautifulSoup as BS
                soup = BS(r.text, "html.parser")
                # Try JSON-LD
                import json as _j
                for script in soup.find_all("script", type="application/ld+json"):
                    try:
                        data = _j.loads(script.string or "")
                        items = data if isinstance(data, list) else [data]
                        for item in items:
                            if item.get("@type") in ("Event","MusicEvent"):
                                sd = item.get("startDate","")
                                h = parse_time(sd)
                                if h:
                                    ev["hora"] = h
                                    enriched += 1
                                sala = item.get("location",{})
                                if isinstance(sala,dict) and sala.get("name"):
                                    ev["sala"] = normalize_sala(sala["name"])
                                break
                    except: pass
            time.sleep(0.3)
    if enriched: print(f"    (enriched {enriched} with hora)")
    print(f"  zgzconciertos: {len(evs)}"); return evs

def scrape_aragonenvivo():
    """Aragón en Vivo - usando API REST de The Events Calendar."""
    import json as _json
    evs = []
    
    # Try REST API first (The Events Calendar exposes /wp-json/tribe/events/v1/events)
    api_url = "https://aragonenvivo.com/wp-json/tribe/events/v1/events"
    r = get(api_url + "?per_page=50&status=publish&start_date=" + __import__('datetime').date.today().isoformat())
    if r and len(r.text) > 100:
        try:
            data = _json.loads(r.text)
            for ev in data.get("events", []):
                title = ev.get("title", "").strip()
                if not title or len(title) < 3: continue
                start = ev.get("start_date", "")
                fecha = parse_date(start) or ""
                hora = parse_time(start) or ""
                venue = ev.get("venue", {})
                sala = venue.get("venue", "") if isinstance(venue, dict) else ""
                url = ev.get("url", "")
                img = ""
                img_data = ev.get("image", {})
                if isinstance(img_data, dict):
                    img = img_data.get("url", "")
                evs.append(make_event(title, fecha, hora, sala or "Zaragoza", url, img))
            print(f"  aragonenvivo (API): {len(evs)}")
            if evs: return evs
        except Exception as e:
            print(f"  aragonenvivo API error: {e}")
    
    # Fallback: scrape listing (without individual page visits)
    for url in ["https://aragonenvivo.com/eventos/", "https://aragonenvivo.com/agenda/"]:
        batch = []
        r2 = get(url)
        if not r2: continue
        from bs4 import BeautifulSoup as BS
        soup = BS(r2.text, "html.parser")
        # Extract from JSON-LD in the listing page itself
        for script in soup.find_all("script", type="application/ld+json"):
            try:
                data = _json.loads(script.string or "")
                items = data if isinstance(data, list) else [data]
                for item in items:
                    if item.get("@type") in ("Event", "MusicEvent"):
                        title = item.get("name","").strip()
                        if not title: continue
                        sd = item.get("startDate","")
                        fecha = parse_date(sd) or ""
                        hora = parse_time(sd) or ""
                        loc = item.get("location",{})
                        sala = loc.get("name","Zaragoza") if isinstance(loc,dict) else "Zaragoza"
                        url2 = item.get("url","")
                        img = ""
                        img_val = item.get("image","")
                        img = img_val if isinstance(img_val,str) else (img_val[0] if isinstance(img_val,list) and img_val else "")
                        batch.append(make_event(title, fecha, hora, sala, url2, img))
            except: pass
        if batch:
            evs = batch
            break
    
    # If still no results, use generic scraper
    if not evs:
        for url in ["https://aragonenvivo.com/eventos/", "https://aragonenvivo.com/agenda/"]:
            evs = scrape_generic(url, "Zaragoza", "https://aragonenvivo.com")
            if evs: break
    
    print(f"  aragonenvivo: {len(evs)}")
    return evs


def scrape_enjoyzaragoza():
    evs = scrape_generic("https://www.enjoyzaragoza.es/conciertos-zaragoza/", "Zaragoza", "https://www.enjoyzaragoza.es")
    print(f"  enjoyzaragoza: {len(evs)}"); return evs

def scrape_sala_lopez():
    evs = []
    for url in ["https://salalopez.com/eventos/"]:
        evs = scrape_generic(url, "Sala López", "https://salalopez.com")
        if evs: break
    print(f"  sala lopez: {len(evs)}"); return evs

def scrape_sala_oasis():
    evs = []
    for url in ["https://www.salaoasis.com/agenda-oasis/",
                "https://www.salaoasis.com/agenda/",
                "https://www.salaoasis.com/"]:
        evs = scrape_generic(url, "Sala Oasis", "https://www.salaoasis.com")
        if evs: break
    print(f"  sala oasis: {len(evs)}"); return evs

def scrape_creedence():
    evs = []
    for url in ["https://creedencesound.com/sala-creedence-conciertos-y-sesiones", "https://creedencesound.com/"]:
        evs = scrape_generic(url, "Sala Creedence", "https://creedencesound.com")
        if evs: break
    print(f"  creedence: {len(evs)}"); return evs

def scrape_lata_bombillas():
    evs = []
    for url in ["https://lalatadebombillas.es/eventos/", "https://lalatadebombillas.es/conciertos/",
                "https://lalatadebombillas.es/programacion/", "https://lalatadebombillas.es/"]:
        evs = scrape_generic(url, "La Lata de Bombillas", "https://lalatadebombillas.es")
        if evs: break
    print(f"  lata bombillas: {len(evs)}"); return evs

# rockandbluescafe.com no publica su agenda en HTML: la incrusta en un iframe
# de su plataforma de entradas, donde cada evento lleva la fecha exacta en la
# ruta de su cartel (backoffice/eventos/27-08-2026-COPACABANA/foto.jpg).
RB_IFRAME = "https://www.sweetcaroline.app/programacion8.php"

def scrape_rock_blues():
    r = get(RB_IFRAME)
    if not r:
        print("  rock&blues: sin respuesta del iframe de programacion")
        return []
    soup = BeautifulSoup(r.text, "html.parser")
    evs = []
    for a in soup.select("a.listing-item-container"):
        titulo_el = a.select_one(".listing-item-content h3, .listing-item-content h4")
        if not titulo_el: continue
        titulo = normalize(titulo_el.get_text())
        if not titulo or len(titulo) < 3: continue
        img_el = a.select_one("img")
        img_src = (img_el.get("data-src") or img_el.get("src") or "") if img_el else ""
        fecha = ""
        m = re.search(r"(\d{2})-(\d{2})-(\d{4})", img_src)
        if m:
            fecha = f"{m.group(3)}-{m.group(2)}-{m.group(1)}"
        else:
            # Respaldo: el texto suelto tipo "27 AGOSTO", sin ano
            sueltos = [sp.get_text() for sp in a.select(".listing-item-content span")]
            for txt in sueltos:
                f = parse_date(txt)
                if f: fecha = f; break
        href = a.get("href", "") or RB_IFRAME
        # Los enlaces del iframe son relativos: sin esto la tarjeta apuntaba a
        # pinplan.es/programacion10.php?idevento=... y daba 404
        if href and not href.startswith("http"):
            href = "https://www.sweetcaroline.app/" + href.lstrip("/")
        if img_src and not img_src.startswith("http"):
            img_src = "https://www.sweetcaroline.app/" + img_src.lstrip("/")
        evs.append(make_event(titulo, fecha, "", "Rock & Blues Café", href, img_src.split("?")[0]))
    con_fecha = sum(1 for e in evs if e["fecha"])
    print(f"  rock&blues: {len(evs)} ({con_fecha} con fecha)")
    return evs

def scrape_teatro_esquinas():
    evs = []
    for url in ["https://www.teatrodelasesquinas.com/es/programacion-de-teatro-y-conciertos.html?ordre=data_propera_funcio&daterange=&filtre_espais%5B%5D=all&cf%5B9%5D%5B%5D=17&filtre_historic=0",
                "https://www.teatrodelasesquinas.com/es/programacion-de-teatro-y-conciertos.html"]:
        evs = scrape_generic(url, "Teatro de las Esquinas", "https://www.teatrodelasesquinas.com")
        if evs: break
    print(f"  teatro esquinas: {len(evs)}"); return evs

def scrape_auditorio():
    """El titulo y su fecha viven en bloques hermanos, no anidados: de ahi que el
    scraping generico no lograse emparejarlos. Ademas la imagen usa lazyload."""
    r = get("https://auditoriozaragoza.com/agenda/")
    if not r:
        print("  auditorio: sin respuesta")
        return []
    soup = BeautifulSoup(r.text, "html.parser")
    evs, no_conciertos, vistos = [], 0, set()
    for fecha_el in soup.select(".fecha-agenda"):
        h = fecha_el.find_previous("h4", class_="qode-post-title")
        if not h: continue
        a = h.select_one("a[href]")
        if not a: continue
        titulo = normalize(a.get_text())
        if not titulo or len(titulo) < 3: continue
        fh = fecha_el.get_text()
        fecha = parse_date(fh) or ""
        clave = (titulo.lower(), fecha)
        if clave in vistos: continue
        vistos.add(clave)
        # El Auditorio tambien programa teatro, danza y familiar: solo conciertos
        cat_el = h.find_previous(class_="qode-category-name")
        categoria = _slug(cat_el.get_text()) if cat_el else ""
        if categoria and categoria not in ("concierto", "conciertos", "musica"):
            no_conciertos += 1
            continue
        img_el = h.find_previous("img")
        img = (img_el.get("data-src") or img_el.get("src") or "") if img_el else ""
        if img.startswith("data:"): img = ""
        evs.append(make_event(titulo, fecha, parse_time(fh),
                              "Auditorio de Zaragoza", a["href"], img))
    con_fecha = sum(1 for e in evs if e["fecha"])
    print(f"  auditorio: {len(evs)} ({con_fecha} con fecha, {no_conciertos} descartados por no ser musica)")
    return evs

AM_FEED = "https://www.aragonmusical.com/agenda/feed/"
# Imagen comodin que la fuente pone cuando el evento no tiene cartel propio:
# es preferible dejar el campo vacio y que la web use su propio fondo.
AM_IMG_GENERICA = "Agenda-de-conciertos-en-Zaragoza-Huesca-y-Teruel"

def _am_campo(desc, etiqueta):
    """Extrae un campo del bloque '<strong>Etiqueta:</strong> valor <br />'."""
    m = re.search(r"<strong>\s*%s\s*:?\s*</strong>(.*?)<br" % etiqueta, desc, re.S | re.I)
    if not m: return ""
    return normalize(re.sub(r"<[^>]+>", " ", m.group(1)))

def _es_zaragoza_ciudad(localidad, sala):
    """PinPlan es la agenda de Zaragoza ciudad: la fuente cubre todo Aragon."""
    loc = _slug(localidad)
    if loc: return loc == "zaragoza"
    # Sin localidad, aceptamos solo si la sala es una de las conocidas de la ciudad
    return _slug(sala) in _SALA_SLUGS

def scrape_aragonmusical_feed():
    r = get(AM_FEED, timeout=45)
    if not r:
        print("  aragonmusical (feed): sin respuesta")
        return []
    xml = r.text
    evs, fuera = [], 0
    for item in re.findall(r"<item>(.*?)</item>", xml, re.S):
        def campo(tag):
            m = re.search(r"<%s>(.*?)</%s>" % (tag, tag), item, re.S)
            if not m: return ""
            return _html.unescape(re.sub(r"<!\[CDATA\[|\]\]>", "", m.group(1))).strip()
        titulo = campo("title")
        link = campo("link")
        if not titulo or not link: continue
        desc = _html.unescape(re.search(r"<description>(.*?)</description>", item, re.S).group(1)) \
               if re.search(r"<description>", item, re.S) else ""
        fh = _am_campo(desc, "Fecha/Hora")
        # Fecha del concierto: la del propio bloque; si falta, la de pubDate
        fecha = ""
        m = re.search(r"(\d{2})/(\d{2})/(\d{4})", fh)
        if m:
            fecha = f"{m.group(3)}-{m.group(2)}-{m.group(1)}"
        else:
            pd = campo("pubDate")
            try:
                from email.utils import parsedate_to_datetime
                fecha = (parsedate_to_datetime(pd) + timedelta(hours=2)).strftime("%Y-%m-%d")
            except Exception:
                fecha = ""
        # Hora: '0:00 h.' significa "sin hora anunciada", no medianoche
        hora = ""
        mh = re.search(r"(\d{1,2}):(\d{2})\s*h", fh)
        if mh and not (mh.group(1) in ("0", "00") and mh.group(2) == "00"):
            hora = f"{int(mh.group(1)):02d}:{mh.group(2)}"
        sala = _am_campo(desc, "Sala/Espacio")
        localidad = _am_campo(desc, "Localidad")
        if not _es_zaragoza_ciudad(localidad, sala):
            fuera += 1
            continue
        img = ""
        mi = re.search(r'<img[^>]+src="([^"]+)"', desc)
        if mi and AM_IMG_GENERICA not in mi.group(1):
            img = mi.group(1)
        evs.append(make_event(titulo, fecha, hora, sala or "Zaragoza", link, img))
    con_hora = sum(1 for e in evs if e["hora"])
    print(f"  aragonmusical (feed): {len(evs)} en Zaragoza ciudad "
          f"({con_hora} con hora), {fuera} descartados por estar fuera de la ciudad")
    return evs

def scrape_aragonmusical():
    """Feed RSS primero (trae hora y localidad); el HTML solo si el feed falla."""
    evs = scrape_aragonmusical_feed()
    if evs: return evs
    print("  feed sin resultados: recurro al HTML (sin dato de localidad)")
    return scrape_aragonmusical_html()

def scrape_aragonmusical_html():
    evs = scrape_generic("https://www.aragonmusical.com/conciertos-en-zaragoza/", "Zaragoza", "https://www.aragonmusical.com")
    evs = [e for e in evs if "zaragoza" in (e["sala"] or "").lower() or e["sala"] == "Zaragoza"]
    print(f"  aragonmusical (HTML): {len(evs)}"); return evs

def scrape_taquilla():
    evs = scrape_generic("https://www.taquilla.com/conciertos/zaragoza", "Zaragoza", "https://www.taquilla.com")
    print(f"  taquilla: {len(evs)}"); return evs

def scrape_songkick():
    events = []
    r = get("https://www.songkick.com/es/metro-areas/28809-spain-zaragoza")
    if not r: print("  songkick: 0"); return events
    soup = BeautifulSoup(r.text, "html.parser")
    for li in soup.select("li.event, .event-listings li, .concerts-list li"):
        title_el = li.select_one(".summary strong, h3, strong")
        date_el = li.select_one("time, .date")
        loc_el = li.select_one(".venue-name, .location")
        link_el = li.select_one("a[href]")
        title = normalize(title_el.get_text()) if title_el else ""
        if not title or len(title) < 3: continue
        fecha_raw = (date_el.get("datetime","") or date_el.get_text()) if date_el else ""
        href = link_el["href"] if link_el else ""
        if href and not href.startswith("http"): href = "https://www.songkick.com" + href
        events.append(make_event(title, parse_date(fecha_raw) or "", parse_time(fecha_raw),
            normalize(loc_el.get_text()) if loc_el else "Zaragoza", href))
    print(f"  songkick: {len(events)}"); return events

def scrape_green_heart():
    evs = []
    for url in ["https://elcorazonverdebar.com/agenda/", "https://elcorazonverdebar.com/"]:
        evs = scrape_generic(url, "El Corazón Verde", "https://elcorazonverdebar.com")
        if evs: break
    print(f"  green heart: {len(evs)}"); return evs

def scrape_setlistfm(api_key=None):
    if not api_key:
        api_key = os.environ.get('SETLISTFM_API_KEY','')
    if not api_key:
        print('  setlist.fm: no API key'); return []
    """Setlist.fm — upcoming concerts in Zaragoza."""
    events = []
    headers = {
        "x-api-key": api_key,
        "Accept": "application/json",
        "Accept-Language": "es"
    }
    today = date.today().isoformat()
    cutoff = (date.today() + timedelta(days=30)).isoformat()

    try:
        # Search upcoming events in Zaragoza
        url = "https://api.setlist.fm/rest/1.0/search/setlists"
        params = {
            "cityName": "Zaragoza",
            "countryCode": "ES",
            "p": 1
        }
        r = requests.get(url, headers=headers, params=params, timeout=12)
        if r.status_code != 200:
            print(f"  setlist.fm: HTTP {r.status_code}")
            return events
        data = r.json()
        setlists = data.get("setlist", [])
        for sl in setlists:
            # eventDate format: dd-MM-yyyy
            fecha_raw = sl.get("eventDate", "")
            if fecha_raw:
                parts = fecha_raw.split("-")
                if len(parts) == 3:
                    fecha = f"{parts[2]}-{parts[1]}-{parts[0]}"
                else:
                    continue
            else:
                continue
            # Only future events
            if fecha < today or fecha > cutoff:
                continue
            artist = sl.get("artist", {}).get("name", "")
            if not artist:
                continue
            venue = sl.get("venue", {})
            sala = venue.get("name", "Zaragoza")
            ciudad = venue.get("city", {}).get("name", "")
            if ciudad.lower() != "zaragoza":
                continue
            events.append(make_event(
                artist,
                fecha,
                "",  # setlist.fm doesn't provide time
                sala,
                sl.get("url", ""),
                "",
                ""
            ))
    except Exception as e:
        print(f"  setlist.fm error: {e}")

    print(f"  setlist.fm: {len(events)}")
    return events

def scrape_casa_loco():
    evs = []
    for url in ["https://www.locozaragozadiscoteca.com/",
                "https://www.arenarock.es/sala/la-casa-del-loco/",
                "https://lacasadelloco.es/"]:
        evs = scrape_generic(url, "La Casa del Loco", "https://www.locozaragozadiscoteca.com")
        if evs: break
    print(f"  casa del loco: {len(evs)}"); return evs

def scrape_arenarock():
    """Arenarock.es - aggregator for Zaragoza venues."""
    evs = scrape_generic("https://www.arenarock.es/eventos/", "Zaragoza", "https://www.arenarock.es")
    # Filter only Zaragoza events
    evs = [e for e in evs if not e["sala"] or "zaragoza" in e["sala"].lower()
           or e["sala"] in ["Zaragoza", "La Casa del Loco", "Sala Z", "Sala Oasis",
                             "Rock & Blues Café", "Sala Creedence"]]
    print(f"  arenarock: {len(evs)}"); return evs


def scrape_shazam():
    """Shazam events for Zaragoza."""
    events = []
    try:
        url = "https://www.shazam.com/es-es/events/zaragoza-espa%C3%B1a"
        r = get(url)
        if not r: print("  shazam: 0"); return events
        from bs4 import BeautifulSoup
        soup = BeautifulSoup(r.text, "html.parser")
        # Shazam uses JSON-LD for events
        import json as _json
        for script in soup.find_all("script", type="application/ld+json"):
            try:
                data = _json.loads(script.string or "")
                items = data if isinstance(data, list) else [data]
                for item in items:
                    if item.get("@type") not in ("Event", "MusicEvent"): continue
                    title = item.get("name","")
                    fecha_raw = item.get("startDate","")
                    location = item.get("location",{})
                    sala = location.get("name","Zaragoza") if isinstance(location, dict) else "Zaragoza"
                    img = ""
                    if isinstance(item.get("image"), str): img = item["image"]
                    elif isinstance(item.get("image"), list) and item["image"]: img = item["image"][0]
                    href = item.get("url","")
                    if title and fecha_raw:
                        events.append(make_event(title, parse_date(fecha_raw) or "", parse_time(fecha_raw), sala, href, img))
            except: pass
        # Also try to find events in page data
        if not events:
            for el in soup.select("[data-testid*='event'], .event-card, [class*='EventCard']"):
                title_el = el.select_one("h2, h3, [class*='title'], [class*='name']")
                date_el = el.select_one("time, [class*='date'], [class*='Date']")
                title = normalize(title_el.get_text()) if title_el else ""
                if not title or len(title) < 2: continue
                fecha_raw = (date_el.get("datetime","") or date_el.get_text()) if date_el else ""
                events.append(make_event(title, parse_date(fecha_raw) or "", "", "Zaragoza", url))
    except Exception as e:
        print(f"  shazam error: {e}")
    print(f"  shazam: {len(events)}")
    return events

def scrape_auditorio_detail():
    """Auditorio Zaragoza - visit each event page to get the date."""
    events = []
    try:
        r = get("https://auditoriozaragoza.com/agenda/conciertos/")
        if not r: print("  auditorio_detail: 0"); return events
        from bs4 import BeautifulSoup
        soup = BeautifulSoup(r.text, "html.parser")
        # Get all event links
        links = []
        for a in soup.select("a[href*='/programacion/'], a[href*='/evento/'], a[href*='/concierto/']"):
            href = a.get("href","")
            if href and href not in links:
                links.append(href)
        links = links[:30]  # Max 30 to avoid timeout
        for href in links:
            if not href.startswith("http"):
                href = "https://auditoriozaragoza.com" + href
            ev_r = get(href, timeout=8)
            if not ev_r: continue
            ev_soup = BeautifulSoup(ev_r.text, "html.parser")
            title_el = ev_soup.select_one("h1, .entry-title, [class*='title']")
            title = normalize(title_el.get_text()) if title_el else ""
            if not title or len(title) < 3: continue
            # Find date
            fecha_raw = ""
            date_el = ev_soup.select_one("time[datetime], [itemprop='startDate'], [class*='fecha'], [class*='date']")
            if date_el:
                fecha_raw = date_el.get("datetime","") or date_el.get("content","") or date_el.get_text()
            # Try meta tags
            if not parse_date(fecha_raw):
                meta = ev_soup.find("meta", {"itemprop": "startDate"}) or ev_soup.find("meta", {"property": "event:start_time"})
                if meta: fecha_raw = meta.get("content","")
            img_el = ev_soup.select_one("meta[property='og:image']")
            img = img_el.get("content","") if img_el else ""
            events.append(make_event(title, parse_date(fecha_raw) or "", "", "Auditorio de Zaragoza", href, img))
            time.sleep(0.5)
    except Exception as e:
        print(f"  auditorio_detail error: {e}")
    print(f"  auditorio_detail: {len(events)}")
    return events


def scrape_auditorio_rss():
    """Auditorio Zaragoza RSS feed - fechas fiables."""
    import xml.etree.ElementTree as ET
    events = []
    urls = [
        # /agenda/conciertos/feed/ existe pero devuelve 0 items
        "https://auditoriozaragoza.com/programacion/feed/",
        "https://auditoriozaragoza.com/feed/",
    ]
    for url in urls:
        r = get(url)
        if not r: continue
        try:
            root = ET.fromstring(r.content)
            ns = {'content': 'http://purl.org/rss/1.0/modules/content/',
                  'dc': 'http://purl.org/dc/elements/1.1/'}
            for item in root.findall('.//item'):
                title = (item.findtext('title') or '').strip()
                if not title or len(title) < 3: continue
                link = (item.findtext('link') or '').strip()
                # Try multiple date fields
                fecha_raw = (item.findtext('pubDate') or
                            item.findtext('dc:date', namespaces=ns) or
                            item.findtext('{http://purl.org/dc/elements/1.1/}date') or '')
                # pubDate format: "Mon, 16 May 2026 10:00:00 +0000"
                fecha = parse_date(fecha_raw)
                if not fecha: continue
                img_el = None
                enclosure = item.find('enclosure')
                img = enclosure.get('url','') if enclosure is not None else ''
                desc = (item.findtext('description') or '').strip()
                from bs4 import BeautifulSoup as BS
                if desc:
                    img_soup = BS(desc, 'html.parser')
                    img_tag = img_soup.find('img')
                    if img_tag and not img:
                        img = img_tag.get('src','')
                # Skip if fecha looks like old publication date
                from datetime import date as _date
                if fecha and fecha >= _date.today().isoformat():
                    events.append(make_event(title, fecha, '', 'Auditorio de Zaragoza', link, img))
            if events: break
        except Exception as e:
            print(f"  auditorio_rss error: {e}")
            continue
    print(f"  auditorio_rss: {len(events)}")
    return events

def scrape_ibercaja_auditorio():
    """Entradas Ibercaja - Auditorio de Zaragoza."""
    evs = scrape_generic(
        "https://entradas.ibercaja.es/eventos/zaragoza/auditorio-de-zaragoza-princesa-leonor/",
        "Auditorio de Zaragoza",
        "https://entradas.ibercaja.es"
    )
    print(f"  ibercaja_auditorio: {len(evs)}")
    return evs

def scrape_taquilla_zgz():
    """Taquilla.com - conciertos en Zaragoza."""
    evs = []
    for url in [
        "https://www.taquilla.com/conciertos?t10city=Zaragoza",
        "https://www.taquilla.com/zaragoza/auditorio-de-zaragoza",
    ]:
        batch = scrape_generic(url, "Zaragoza", "https://www.taquilla.com")
        evs.extend(batch)
    # deduplicate within this source
    seen = set()
    unique = []
    for e in evs:
        k = (e["titulo"].lower()[:40], e["fecha"])
        if k not in seen:
            seen.add(k)
            unique.append(e)
    print(f"  taquilla_zgz: {len(unique)}")
    return unique


def scrape_ayuntamiento_zgz():
    """API de datos abiertos del Ayuntamiento de Zaragoza."""
    import json as _j
    events = []
    try:
        from datetime import date, timedelta
        today = date.today().isoformat()
        cutoff = (date.today() + timedelta(days=180)).isoformat()
        url = (f"https://www.zaragoza.es/sede/servicio/cultura/evento.json"
               f"?fl=id,title,startDate,endDate,location,category,description,image"
               f"&start=0&rows=100&sort=startDate+asc"
               f"&fq=startDate:[{today}T00:00:00Z+TO+{cutoff}T23:59:59Z]")
        r = get(url)
        if not r: print("  ayto_zgz: 0"); return events
        data = _j.loads(r.text)
        items = (data.get("result") or data.get("results") or
                 data.get("response", {}).get("docs", []) or [])
        if isinstance(items, dict): items = items.get("docs", [])
        for item in items:
            title = item.get("title","").strip()
            if not title: continue
            sd = item.get("startDate","")
            fecha = parse_date(sd) or ""
            hora = parse_time(sd) or ""
            loc = item.get("location","")
            sala = ""
            if isinstance(loc, dict):
                sala = loc.get("title","") or loc.get("name","")
            elif isinstance(loc, str):
                sala = loc
            img = item.get("image","")
            if isinstance(img, list): img = img[0] if img else ""
            url2 = f"https://www.zaragoza.es/sede/servicio/cultura/evento/{item.get('id','')}"
            events.append(make_event(title, fecha, hora, sala or "Zaragoza", url2, img))
    except Exception as e:
        print(f"  ayto_zgz error: {e}")
    print(f"  ayto_zgz: {len(events)}")
    return events

def scrape_enterat():
    evs = scrape_generic("https://www.enterat.com/ocio/agenda-conciertos-zaragoza.php","Zaragoza","https://www.enterat.com")
    print(f"  enterat: {len(evs)}"); return evs

def scrape_laganzua():
    # Raspar su HTML devolvia 4 de los 24 eventos que publica en JSON-LD
    return scrape_jsonld("https://www.laganzua.net/conciertos/aragon", "la ganzua")

def scrape_zaragenda():
    evs = scrape_generic("https://zaragenda.com","Zaragoza","https://zaragenda.com")
    print(f"  zaragenda: {len(evs)}"); return evs


def fetch_artist_image(titulo):
    """Desactivado temporalmente - MusicBrainz da 503."""
    return ""


def normalize_title(t):
    """Normalize title for dedup comparison."""
    t = t.lower().strip()
    # Remove common suffixes like "+ support", "en directo", etc.
    t = re.sub(r'\s*[+&]\s*.{1,30}$', '', t)
    t = re.sub(r'\s+(en\s+directo|directo|live|tour|\d{4})\s*$', '', t)
    # Remove all non-alphanumeric
    t = re.sub(r'[^a-záéíóúüñ0-9]', '', t)
    return t[:30]

GARBAGE_TITLES = {
    "saltar al contenido", "lista", "ver todos", "entradas", "comprar",
    "más info", "agenda", "eventos", "conciertos", "programación", "inicio",
    "home", "menu", "menú", "siguiente", "anterior", "cerrar",
    "leer más", "read more", "ver más", "ver todo", "all events",
    "día", "mes", "semana", "hoy", "mañana", "week", "month", "day",
    "próximos eventos", "próximos conciertos", "próximas actuaciones",
    "comprar entradas", "compra entradas", "compra de entradas",
    "eventos anteriores", "« eventos anteriores", "eventos anteriores »",
    "ical", "icalendar", "añadir google calendar",
    "la casa del loco", "sala oasis", "sala lópez", "sala creedence",
    "rock & blues café", "rock &amp; blues café",
}

# Las sesiones semanales de local (Molissesion y similares) se descartaban aqui.
# Ahora se publican, pero marcadas como recurrentes para que queden por debajo de
# los conciertos programados del mismo dia. Ver marcar_recurrentes().
GARBAGE_PATTERNS = []

GARBAGE_URL_PATTERNS = ["/eventos/hoy", "/eventos/mes", "/eventos/semana", 
                         "/agenda/hoy", "/agenda/mes", "/#content"]

def is_garbage(titulo, url=""):
    t = titulo.lower().strip()
    if t in GARBAGE_TITLES: return True
    if len(t) < 3: return True
    if t.startswith("saltar") or t.startswith("skip"): return True
    if t in {"día", "mes", "hoy", "semana", "año", "lista", "todo"}: return True
    for pat in GARBAGE_URL_PATTERNS:
        if pat in url: return True
    for pat in GARBAGE_PATTERNS:
        if t.startswith(pat): return True
    # Titles that are just sala names (no artist)
    if t in normalize_sala(t).lower(): pass  # keep
    return False



# Ruido habitual en los titulos: la misma actuacion aparece en varias fuentes como
# "Flamin' Groovies", "FLAMIN' GROOVIES." y "The Flamin Groovies".
_TITULO_RUIDO = re.compile(r"\b(the|los|las|el|la|feat|ft|usa|uk|esp|tributo a|en concierto|en directo|gira)\b")

def _titulo_clave(t):
    return re.sub(r"\s+", "", _TITULO_RUIDO.sub(" ", _slug(t)))

def _riqueza(e):
    """Cuanta informacion aporta un evento; a igualdad, mejor el titulo mas limpio."""
    return (bool(e["imagen"]) + bool(e["hora"]) + bool(e["descripcion"]), -len(e["titulo"]))

def fusionar_similares(events):
    """Une eventos del mismo dia y sala cuyos titulos son variantes del mismo nombre."""
    from difflib import SequenceMatcher
    grupos = {}
    for e in events:
        grupos.setdefault((e["fecha"], _slug(e["sala"])), []).append(e)
    salida = []
    for grupo in grupos.values():
        elegidos = []
        for e in grupo:
            clave = _titulo_clave(e["titulo"])
            gemelo = None
            for ya in elegidos:
                otra = _titulo_clave(ya["titulo"])
                if not clave or not otra: continue
                parecido = (clave == otra or clave in otra or otra in clave
                            or SequenceMatcher(None, clave, otra).ratio() >= 0.85)
                if parecido:
                    gemelo = ya
                    break
            if gemelo is None:
                elegidos.append(e)
            elif _riqueza(e) > _riqueza(gemelo):
                elegidos[elegidos.index(gemelo)] = e
        salida.extend(elegidos)
    return salida

def deduplicate(events):
    events = [e for e in events if e["fecha"]]
    events = [e for e in events if not is_garbage(e["titulo"], e.get("url",""))]
    seen = {}
    for e in events:
        key = (e["titulo"].lower().strip()[:50], e["fecha"])
        if key not in seen:
            seen[key] = e
        else:
            ex = seen[key]
            score_new = bool(e["imagen"]) + bool(e["hora"]) + bool(e["descripcion"]) + (e["sala"] not in ["Zaragoza",""])
            score_ex  = bool(ex["imagen"]) + bool(ex["hora"]) + bool(ex["descripcion"]) + (ex["sala"] not in ["Zaragoza",""])
            if score_new > score_ex: seen[key] = e
    unicos = list(seen.values())
    fusionados = fusionar_similares(unicos)
    if len(fusionados) < len(unicos):
        print(f"  Variantes del mismo concierto fusionadas: {len(unicos)-len(fusionados)}")
    return fusionados

DIAS_SEMANA = ("lunes", "martes", "miercoles", "jueves", "viernes", "sabado", "domingo")

def marcar_recurrentes(events):
    """Marca las sesiones fijas de local, para ordenarlas tras los conciertos del dia.

    Se consideran recurrentes por dos senales independientes:
      - el titulo empieza por un dia de la semana ("Viernes Molissesion...")
      - el mismo titulo y sala se repiten en fechas separadas por multiplos de 7 dias
    """
    grupos = {}
    for e in events:
        grupos.setdefault((_slug(e["titulo"]), _slug(e["sala"])), []).append(e)
    for (titulo_slug, _), grupo in grupos.items():
        empieza_por_dia = titulo_slug.startswith(DIAS_SEMANA)
        semanal = False
        fechas = sorted({e["fecha"] for e in grupo if e["fecha"]})
        if len(fechas) >= 2:
            try:
                ds = [date.fromisoformat(f) for f in fechas]
                saltos = [(b - a).days for a, b in zip(ds, ds[1:])]
                mismo_dia = len({d.weekday() for d in ds}) == 1
                cada_7 = all(x % 7 == 0 for x in saltos)
                # con solo dos fechas exigimos que sean consecutivas (7 o 14 dias):
                # si no, dos conciertos lejanos coinciden de dia por pura casualidad
                seguidas = len(fechas) >= 3 or max(saltos) <= 14
                semanal = mismo_dia and cada_7 and seguidas
            except ValueError:
                semanal = False
        if empieza_por_dia or semanal:
            for e in grupo:
                e["recurrente"] = True
    return events

def filter_future(events):
    today = date.today().isoformat()
    cutoff = (date.today() + timedelta(days=180)).isoformat()
    # Filter out past events and events more than 6 months away
    return [e for e in events if e["fecha"] and today <= e["fecha"] <= cutoff]

DIAS_DE_GRACIA = 10

def fusionar_con_anterior(nuevos, ruta_anterior):
    """Conserva los eventos ya conocidos cuya fuente no ha respondido en este run.

    El scraper regeneraba el fichero desde cero, asi que una caida puntual de una
    fuente borraba sus conciertos de la web. aragonenvivo.com, por ejemplo, da
    ConnectTimeout intermitente desde el runner de GitHub: la agenda pasaba de 163
    a 135 eventos y volvia, y los conciertos aparecian y desaparecian solos.

    Un evento se mantiene mientras siga siendo futuro y se haya confirmado en los
    ultimos DIAS_DE_GRACIA dias. Pasado ese plazo se deja caer: si ninguna fuente
    lo menciona en diez dias, lo normal es que se haya cancelado.
    """
    hoy = date.today().isoformat()
    limite = (date.today() - timedelta(days=DIAS_DE_GRACIA)).isoformat()
    for e in nuevos:
        e["visto"] = hoy
    indice = {(_titulo_clave(e["titulo"]), e["fecha"]): e for e in nuevos}
    try:
        with open(ruta_anterior, encoding="utf-8") as f:
            previos = json.load(f).get("eventos", [])
    except (OSError, ValueError):
        return nuevos, 0
    rescatados = 0
    for viejo in previos:
        clave = (_titulo_clave(viejo.get("titulo", "")), viejo.get("fecha", ""))
        if clave in indice: continue
        if not viejo.get("fecha") or viejo["fecha"] < hoy: continue
        if viejo.get("visto", "") < limite: continue
        indice[clave] = viejo
        rescatados += 1
    return list(indice.values()), rescatados

def sort_events(events):
    return sorted(events, key=lambda e: (e["fecha"] or "9999",
                                        1 if e.get("recurrente") else 0,
                                        e["hora"] or "99:99"))

def main():
    print(f"\nPinPlan scraper — {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    all_events = []
    scrapers = [
        ("ZGZ Conciertos",       scrape_zgzconciertos),
        ("Aragón en Vivo",       scrape_aragonenvivo),
        ("Enjoy Zaragoza",       scrape_enjoyzaragoza),
        ("Sala López",           scrape_sala_lopez),
        ("Sala Oasis",           scrape_sala_oasis),
        ("Sala Creedence",       scrape_creedence),
        ("La Lata de Bombillas", scrape_lata_bombillas),
        ("Rock & Blues Café",    scrape_rock_blues),
        ("Teatro Esquinas",      scrape_teatro_esquinas),
        ("Auditorio Zaragoza",   scrape_auditorio),
        ("Auditorio RSS",       scrape_auditorio_rss),
        ("Ibercaja Auditorio",  scrape_ibercaja_auditorio),
        ("Taquilla ZGZ",        scrape_taquilla_zgz),
        ("Aragón Musical",       scrape_aragonmusical),
        ("Taquilla.com",         scrape_taquilla),
        ("Songkick",             scrape_songkick),
        ("Green Heart",          scrape_green_heart),
        ("Setlist.fm",           scrape_setlistfm),
        ("La Casa del Loco",    scrape_casa_loco),
        ("Arenarock",           scrape_arenarock),
        ("La Ganzua",           scrape_laganzua),
        ("JacksOnLive",         scrape_jacksonlive),
    ]
    por_fuente = []
    for name, fn in scrapers:
        print(f"\n[{name}]")
        try:
            evs = fn()
            all_events.extend(evs)
            por_fuente.append((name, len(evs), ""))
        except Exception as e:
            print(f"  ERROR: {e}")
            por_fuente.append((name, 0, f"{type(e).__name__}: {str(e)[:60]}"))
        time.sleep(1.5)

    # Enrich images for events without one (max 20 to avoid timeout)
    enriched_imgs = 0
    for ev in all_events:
        if not ev.get("imagen") and enriched_imgs < 20:
            img = fetch_artist_image(ev["titulo"])
            if img:
                ev["imagen"] = img
                enriched_imgs += 1
    if enriched_imgs: print(f"  Imágenes enriquecidas: {enriched_imgs}")
    print(f"\nBruto: {len(all_events)}")
    con_fecha = [e for e in all_events if e["fecha"]]
    print(f"  Con fecha: {len(con_fecha)} / Sin fecha: {len(all_events)-len(con_fecha)}")
    # Show unique titles before dedup
    titulos_con_fecha = [(e["titulo"][:40], e["fecha"]) for e in con_fecha]
    from collections import Counter
    title_counts = Counter(e["titulo"].lower().strip()[:50] for e in con_fecha)
    print(f"  Titulos unicos con fecha: {len(title_counts)}")
    print(f"  Top repetidos: {title_counts.most_common(5)}")
    junk = [e for e in all_events if is_junk_title(e["titulo"]) or is_junk_url(e["url"])]
    if junk:
        print(f"  Descartados por no ser un concierto: {len(junk)} -> {sorted(set(e['titulo'] for e in junk))[:8]}")
    all_events = [e for e in all_events if not (is_junk_title(e["titulo"]) or is_junk_url(e["url"]))]
    deduped = deduplicate(all_events)
    print(f"Tras dedup: {len(deduped)}")
    filtered = filter_future(deduped)
    print(f"Tras filter_future: {len(filtered)}")
    # Show what got filtered out
    deduped_fechas = set(e["fecha"] for e in deduped)
    filtered_fechas = set(e["fecha"] for e in filtered)
    lost = deduped_fechas - filtered_fechas
    if lost: print(f"  Fechas eliminadas: {sorted(lost)}")
    all_events = sort_events(marcar_recurrentes(filtered))
    n_rec = sum(1 for e in all_events if e.get("recurrente"))
    if n_rec: print(f"  Sesiones recurrentes (van tras los conciertos del dia): {n_rec}")
    print(f"Limpio: {len(all_events)}")
    if all_events:
        fechas = sorted(set(e["fecha"] for e in all_events))
        print(f"  Fechas: {fechas[0]} → {fechas[-1]}")

    print("\n" + "=" * 64)
    print("RESUMEN POR FUENTE")
    vacias = []
    for name, n, err in por_fuente:
        marca = "ok " if n else "VACIA"
        print(f"  {marca} {name:<24} {n:>4} {err}")
        if not n: vacias.append(name)
    print("\nESTADO HTTP POR DOMINIO")
    for dom in sorted(DIAG):
        d = DIAG[dom]
        print(f"  {dom:<34} {d['estado']:<30} {d['ms']:>6} ms  {d['bytes']:>8} B")
    problemas = {d: v for d, v in DIAG.items() if v["estado"] != "OK"}
    if problemas:
        print(f"\n  {len(problemas)} dominio(s) con problema: {', '.join(sorted(problemas))}")
    if len(vacias) > len(por_fuente) // 2:
        print(f"\n  AVISO: {len(vacias)}/{len(por_fuente)} fuentes vacias. Revisa el estado HTTP de arriba:")
        print("  si predominan timeouts o muros anti-bot, el runner de GitHub esta siendo bloqueado")
        print("  y el scraping debe ejecutarse desde otra IP.")
    print("=" * 64)

    out_path = pathlib.Path(__file__).parent.parent / 'eventos.json'
    all_events, rescatados = fusionar_con_anterior(all_events, out_path)
    all_events = sort_events(all_events)
    if rescatados:
        print(f"  Conservados de runs anteriores (su fuente no respondio hoy): {rescatados}")
    print(f"Publicados: {len(all_events)}")

    output = {"actualizado": datetime.now().isoformat(), "total": len(all_events), "eventos": all_events}
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"Guardado en {out_path} ✓")

if __name__ == "__main__":
    main()
